### ISSUE TITLE
Should the username be set in the JWTToken

### ISSUE THREAD

**Issue by manocha-aman** [rockthejvm/akka-http#1]
JwtAuthorization.createToken accepts the username but it doesn't use it. Should it be set as the subject in the claims?

**Comment by daniel-ciocirlan** [comment]
It's fine to include it in the subject as long as it's unique, which is reasonably the case with usernames/emails. However, just bear in mind that in practice this poses additional problems, as you now need to protect the token because it contains personal information.

**Comment by manocha-aman** [comment]
I thought we need to keep user id in the token otherwise we will not be able to identify which user is making the call? SecurityDomain is only checking if the token is valid but most applications will need to identify the user from the token?

**Comment by daniel-ciocirlan** [comment]
That's true. You can expand the code as you like, to identify the user, check associated permissions to the token, etc.
